#!/bin/bash

rm /sys/fs/bpf/ebpf_backdoor_rop

mkdir -p ./cmake-build-debug && \
  cmake -B ./cmake-build-debug && \
  cmake --build ./cmake-build-debug && \
  bpftool prog load cmake-build-debug/backdoor_rop.c.o /sys/fs/bpf/ebpf_backdoor_rop autoattach && \
  ./cmake-build-debug/loader_rop

# rm /sys/fs/bpf/ebpf_backdoor_rop
